name: Building

on: [push, workflow_dispatch]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          java-version: 20
      - name: Build test project
        run: |
          chmod +x gradlew
          ./gradlew nmpCopyBuildRelease --stacktrace
          tree
      - name: Upload built jar file
        uses: actions/upload-artifact@v4
        with:
          name: ExtendLogs.jar
          path: build/libs/*.jar
